# Generated by Django 6.0 on 2025-12-13 10:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО/Название')),
                ('type', models.CharField(choices=[('individual', 'Физическое лицо'), ('legal', 'Юридическое лицо')], max_length=20, verbose_name='Тип')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(verbose_name='Дата заказа')),
                ('expected_delivery_date', models.DateField(verbose_name='Ожидаемая дата поставки')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата поставки')),
                ('status', models.CharField(choices=[('ordered', 'Заказан'), ('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], max_length=20, verbose_name='Статус поставки')),
            ],
        ),
        migrations.CreateModel(
            name='RetailOutlet',
            fields=[
                ('retail_outlet_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('purchase_order_items_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='Товар')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='retail_outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.retailoutlet', verbose_name='Торговая точка'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('retail_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.retailoutlet', verbose_name='Торговая точка')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('confirmed', 'Подтвержден'), ('in_delivery', 'В доставке'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], max_length=20, verbose_name='Статус заказа')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Персональная скидка (%)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer', verbose_name='Покупатель')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee', verbose_name='Сотрудник')),
                ('retail_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.retailoutlet', verbose_name='Торговая точка')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier', verbose_name='Поставщик'),
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salesorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='Товар')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
