# Generated by Django 6.0 on 2025-12-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_salesorder_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='status',
        ),
    ]
