# Generated by Django 6.0 on 2025-12-17 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_purchaseorder_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='actual_delivery_date',
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Персональная скидка (%)'),
        ),
    ]
